# Supervisor configuration for LEGOFIT website

[program:legofit-flask]
command=/var/www/legofit-explorer.com/venv/bin/gunicorn --bind 127.0.0.1:8050 --workers 3 --timeout 120 --worker-class sync main:server
directory=/var/www/legofit-explorer.com
user=www-data
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/legofit/flask.err.log
stdout_logfile=/var/log/legofit/flask.out.log
environment=PRODUCTION="true",BASE_URL="https://renovation.posifit.eu"

[program:legofit-dash]
command=/var/www/legofit-explorer.com/venv/bin/gunicorn --bind 127.0.0.1:8051 --workers 2 --timeout 300 --worker-class sync wsgi:server
directory=/var/www/legofit-explorer.com
user=www-data
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/legofit/dash.err.log
stdout_logfile=/var/log/legofit/dash.out.log
environment=PRODUCTION="true",BASE_URL="https://renovation.posifit.eu",DASH_PORT="8051"

[group:legofit]
programs=legofit-flask,legofit-dash
priority=999

